- package-lock.json
- package.json
- src/App.js
- src/ListagemDeProdutos.jsx
##O que foi feito?
Esta página deve ficar no path /, renderizável a partir do acesso ao componente <App />.
Mostre a mensagem "Digite algum termo de pesquisa ou escolha uma categoria.".
Adicione o atributo data-testid com o valor home-initial-message no elemento da mensagem.
> [GRUPO 39] - Requisito 2 - CRIAR PÁGINA DE LISTAGEM DE PRODUTOS VAZIA

- package-lock.json
- package.json
- src/App.js
- src/services/api.js
Implementadas as funções:
- getCategories();
- getProductsFromCategoryAndQuery();
> [GROUP 39] Requisito 1

- package-lock.json
- src/App.js
- src/services/api.js
Criação das funções de chamada da API.
> [GROUP-18] Call API

- src/App.js
- src/components/InitialScreen.jsx
- src/components/index.js
Criação do campo de busca e mensagem da tela inicial
> [GROUP-18] Initial Screen

- src/App.js
- src/services/api.js
> [GRUPO 17] Requisito 1 - Implementar módulo de acesso à api do mercado livre

- package-lock.json
- package.json
- src/App.js
- src/components/CategoriesCard.js
- src/pages/CategoriesList.js
- src/services/api.js
O requisito 1 não está passando nos teste. Não sei dizer o motivo. Acabei fazendo o requisito dois junto com o 1. @andreserudo @brenoalv3s @lekaoru
> [GRUPO 11] - Campo de busca da tela principal

- src/services/api.js
Ligamos com a api do mercado livre
> [GRUPO 35] Criada a chamada com a Api.

- .prettierrc
- src/services/api.js
o arquivo .prettier é pra estilização, se configurado localmente voce pode formatar automaticamente o arquivo sem precisar se preocupar com o eslint / avaliador,
> [GRUPO 16] Feito modulo API

- package-lock.json
- package.json
- src/App.js
- src/services/.prettierrc
- src/services/api.js
> [GRUPO 38] Implementação api - Requisito 01

- src/App.js
- src/components/InitialScreen.css
- src/components/InitialScreen.jsx
- src/components/SideBar.jsx
- src/components/index.js
> Main group 18 add sidebar filter categories

- package-lock.json
- package.json
- src/App.js
- src/pages/ProductList.js
Desenvolvido requisito 2 estritamente para que os testes fossem satisfeitos.
> [GRUPO 17] Requisito 2 - Criando pagina de listagem de produtos vazia.

- src/App.js
- src/components/Search.js
Criamos a pasta components e adicionamos à mesma o Search.js. Depois importamos o Search.js no App.js;
> [ Grupo 12 ] adicionamos o campo de busca

- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/services/api.js
Implementação das funções de requisição da API do Mercado Livre
- getCategories.
- getProductsFromCategoryAndQuery
> [Grupo 3] - Implementando requisiçao de API

- package-lock.json
- package.json
- src/App.js
- src/Components/Search.js
- src/index.js
- src/services/api.js
##[GROUP - 08] Project-Frontend-Online-Store
> Request API

- package-lock.json
- package.json
- src/App.js
- src/Components/Search.js
- src/index.js
- src/services/api.js
> Main group 08 resquest search bar

- src/App.js
- src/services/api.js
> Adicionando APIs do Mercado Livre

- src/App.js
- src/services/api.js
First building 27 group TRYBE project.
> Conclusão API

- package-lock.json
- package.json
- src/App.js
- src/components/ProductList.jsx
> [GRUPO 21] Cria tela de busca 

- src/services/api.js
Adicionado a função getProductsFromCategoryAndQuery.
> Implementanto função getProductsFromCategoryAndQuery

- README.md
Objetivo: criar uma versão simplificada, sem persistência no banco de dados, de uma loja online, desenvolvendo em grupo suas funcionalidades de acordo com demandas definidas em um quadro Kanban, em um cenário mais próximo ao do mercado de trabalho. A partir dessas demandas, teremos uma aplicação onde os usuários poderão:
•  Buscar produtos por termos e categorias a partir da API do Mercado Livre;
•  Interagir com os produtos buscados de modo a adicioná-los e removê-los de um carrinho de compras em diferentes quantidades;
•  Visualizar detalhes e avaliações prévias de um produto, bem como criar novas avaliações;
•  E por fim, finalizar a compra (simulada) dos itens selecionados.
> [GRUPO 9] Project Frontend Online Store - initial commit

- package-lock.json
- package.json
- src/App.js
- src/pages/Checkout.js
- src/pages/NotFound.js
- src/pages/ProductDetails.js
- src/pages/ProductsList.js
- src/pages/ShoppingCart.js
- src/pages/index.js
-Criado pasta *pages*
-Criado pasta *components* para colocar os arquivos dos componentes
- React router no App.js para as páginas criadas na pasta *pages*
> [GROUP 05] Feito react router no App.js 

- src/App.js
- src/services/api.js
> [ GRUPO 6 ] Adicionando APIs do Mercado Livre

- .github/workflows/main.yml
- src/services/api.js
-Implementa a função getCategories;
-Implementa a função getProductsFromCategoryAndQuery;
> [GROUP 5] Implementa módulo de acesso à API do Mercado Livre

- .prettierrc
- src/App.js
Criação da barra de pesquisa e frase obrigatória.
> Cria componente de busca

- src/App.js
- src/components/Home.jsx
Criação do campo de busca da tela principal com mensagem "Digite algum termo de pesquisa ou escolha uma categoria".
> [Grupo 3] - Campo de busca tela inicial

- src/services/api.js
Definindo as duas funções já presentes no arquivo api.js, responsáveis pela requisição à Api do Mercado Livre.
> Requisito 1 - Implementar acesso Api

- src/App.js
- src/Components/SearchBar.js
- src/Header.js
- Criado arquivos Header.js e SearchBar.js
- Implementado código do input de pesquisa e a mensagem
> criar pagina de listagem de produtos vazia

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/App.js
- src/pages/Cart.js
- src/pages/home.js
> [GROUP 16] Carrinho

- src/services/api.js
1. É possível realizar a busca das categorias para realizar a listagem no site através da função getCategories();
2. E também buscar um termo específico em um categoria com a função getProductsFromCategoryAndQuery( categoryId, query ), passando os parâmetros correspondentes.
> [Group 12] Acesso a api do MercadoLivre 

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/App.js
- src/Home.js
Criar o campo de busca da tela principal, a listagem de produtos, inicialmente vazia. A listagem vazia deve conter a mensagem "Digite algum termo de pesquisa ou escolha uma categoria" (veja os detalhes do card).
> [GRUPO 09] Requisito 2

- package-lock.json
- package.json
- src/App.js
Requisito 2 - Criando campo de busca.
> Group 31 Cria campo de busca

- .github/workflows/main.yml
- src/services/api.js
Implementei o Modulo que Acessa a API
> [GRUPO 20] Implementaçao do modulo que acessa a API

- .github/workflows/main.yml
- src/services/api.js
> [GRUPO 9] 1 - IMPLEMENTANDO MÓDULO DE ACESSO À API

- src/services/api.js
> Corrigindo endPoint

- src/App.js
- src/services/api.js
Implementação da chamada à API.
> implementação da API

- src/App.js
- src/components/ProductList.js
Eu e o Thiago desenvolvemos um componente a qual o requisito 2 pedia. 
O componente se chama ProductList e retorna um texto informando que a lista está vazia.
> [Grupo 10] Adicionando página ProductList vazia

- .github/workflows/main.yml
> [GRUPO 17] - Ajuste no avaliador do github

- .github/workflows/main.yml
> atualizando arquivo main.yml

- src/components/InitialScreen.jsx
- src/components/SideBar.jsx
Criação e implementação do Sidebar.
> [MAIN-GROUP-18] Sidebar Implementation

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/App.js
- src/pages/Home.jsx
- src/pages/ShoppingCart.jsx
- src/services/api.js
Requisito 3- feito em grupo não precisa de codeReview
> [Grupo-04] Requisito 3

- .github/workflows/main.yml
- package-lock.json
- src/services/api.js
Implementação das APIs requisito 1 - test ok
> [GRUPO-4] Api-implementada

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/App.js
- src/components/ProductList/ProductList.jsx
- src/components/SearchBar/SearchBar.jsx
- src/pages/HomePage.jsx
- src/router.js
Creating homepage, using router.js file.
> [GROUP 28] [PRIORITY 0] [REQUIREMENT 2] [CREATING HOMEPAGE]

- src/App.js
- src/components/Categories.js
- src/services/api.js
criei o Categories.js e fiz uma chamada na api getCategories, depois adicionei o resultado em um state e finalmente mostrei na tela.
> [Grupo 12] criei o menú de categorias

- .github/workflows/main.yml
- package-lock.json
- src/services/api.js
Implementando requisição para API !!
> [group-28][Priority-0][Requirement-1][API-implementation]

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/App.js
- src/services/api.js
Criada funções de requisição á API
> [GRUPO 26] Implementado modulo de acesso a API

- src/App.js
- src/components/CampoDeBusca.jsx
- src/pages/ListagemDeProdutos.jsx
Criar o campo de busca da tela principal, a listagem de produtos, inicialmente vazia. A listagem vazia deve conter a mensagem "Digite algum termo de pesquisa ou escolha uma categoria
> Implementação do requisito 2, prioridade 0

- .github/workflows/main.yml
- src/App.js
Component App renderizado, e criado mensagem solicitada.
> [GRUPO 26] Criado campo de busca inicial vazio

- .github/workflows/main.yml
- src/App.js
- src/services/api.js
> Main group 27 busca api

- package-lock.json
- package.json
- src/App.js
- src/Pages/Home.jsx
- src/Pages/ShearchPage.jsx
- src/components/InitialMessage.jsx
menssagem inicial, 
atualiza o status da pagina de busca com o input
Crio duas novas pastas
> commit salva alterações do mesmo commit feito na main

- src/services/api.js
* Foram implementadas duas funções de implementação da API do Mercado Livre:
1. Busca as categorias
2. Busca os produtos
> implementacao das funcoes getCategories e getProductsFromCategoryAndQuery

- src/App.js
- src/components/ProductList.jsx
- src/components/cartButton.jsx
requisito 03 botão do carrinho - virgílio
> [Grupo 21] requisito 03 botão do carrinho

- .github/workflows/main.yml
> [GRUPO 11] correçao evaluator job

- package-lock.json
- src/App.js
- src/components/SearchBar.js
- src/services/api.js
> Main group 33 fetch api

- src/services/api.js
> [Group 14] Feature requisiçao para API adicionada!

- .github/workflows/main.yml
- src/Components/Search.js
- src/index.js
A tela básica da plataforma é a tela de **listagem de produtos**, onde quem usa buscará o que quer para adicionar ao carrinho e filtrará suas buscas.
> Request Search Bar

- src/components/Categories.js
- src/pages/home.js
Feito aside com as categorias.
> [Group 16] Add aside categories

- .github/workflows/main.yml
- src/services/api.js
> Main group 14 fix error

- .github/workflows/main.yml
- src/App.js
- src/services/api.js
Feitas as mudanças! De 1.4.3 para 1.4.4.
> [GRUPO 29] Mudança arquivo main.yml

- package-lock.json
- package.json
- src/components/index.js
- src/pages/index.js
- src/views/index.js
1. Criação de componentes genéricos com pastas de derivação;
2. Índices relacionais, para facilitar exportação e importação;
3. Criação de estilização dos componentes utilizando 'styled-components'
> [Group 13] Realizado estrutura do projeto.

- package-lock.json
- package.json
- src/components/index.js
- src/pages/index.js
- src/views/index.js
Fui criar o pull request da branch main-group-13 e sem querer criei um draft pull request, para tentar resolver, terminei fechando a branch... desculpa pessoal.
> Fiz um pull request da main-group-13 errado :( 

- src/components/Product.jsx
- src/components/ProductList.jsx
- src/services/api.js
Botão que, ao ser clicado, exibe a lista de produtos baseado no texto digitado pelo usuário no campo de pesquisa.
> [GRUPO 21]Listagem de produtos

- package-lock.json
- package.json
- src/App.js
- src/pages/Home.jsx
> adicionando HomePage

- src/components/Product.js
- src/components/ProductList.js
- src/pages/home.js
> [GRUPO 16] Feito busca e listagem

- package-lock.json
- package.json
- src/App.js
- src/components/ProductList.js
- src/components/ShoppingCart.js
Foi adicionado ao componente ProductList um botão e um elemento de texto com a mensagem "Seu carrinho está vazio" 
Há a ideia de criar também um componente para botões caso seja preciso.
> [Grupo 10] Adicionado um botao e a mensagem  "Seu carrinho está vazio"

- src/components/CategorieFilter.jsx
- src/pages/Home.jsx
- src/services/api.js
Resolve problema de bug no FETCH arquivo CategorieList.
Limpamos histórico de navegador e demos bind na função.
> [GRUPO-4] Main group 4 cria lista

- .github/workflows/main.yml
- src/components/CategoryList.jsx
- src/components/SearchBar.jsx
- src/style/categoryList.css
Adicionada uma lista com todas as categorias retornadas pela Api.
> [Main group 35] Category List

- src/components/Categories.js
> Main group 32 add categories filter

- package-lock.json
- package.json
- src/App.js
- src/pages/listagem.jsx
> requisito 2

- src/pages/ProductsList.jsx
- src/services/api.js
- Alterado o arquivo **api**, excluindo a função **getQuery** e alterando a função **getProductsFromCategoryAndQuery**;
- Implementado requisito 5 para fazer busca de produtos e requisição api, renderizando os produtos pesquisados na tela;
> Main group 39 requisito 5 alteracoes

- .github/workflows/main.yml
- src/App.js
- src/components/ListCategories.jsx
Adicionei o elemento na pagina home , tava so faltando isso pra passar no cypress!
> [GROUP 29] List of categories

- src/App.js
- src/components/ProductList.jsx
- src/components/SearchBar.jsx
Criado componente de listagem de produtos, quando pesquisa algo no input do SearchBar
> [GRUPO 35] Lista de produtos

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/App.js
- src/components/ShoppingCart.jsx
Criei apenas um placeholder para o botão, que vai levar até o componente do carrinho. Ainda é necessário refatorar, pois esses componentes devem ser realocados para ficarem sob um componente pai. Da forma que está, ficou desorganizado, mas ao menos as funcionalidades básicas estão funcionando.
✓ A home deve ter o botão do carrinho de compras
✓ Clicar no botão deve levar à página do carrinho vazio, com a mensagem 'Seu carrinho está vazio' nela
> [GRUPO 35] Botão Shopping Cart - Placeholder

- package.json
- src/App.js
- src/components/ProductsList.js
- src/components/ShoppingCartButton.js
- src/icons/IconShoppingCart.js
- src/pages/ShoppingCart.js
- src/services/api.js
- Adicionado página ShoppingCart com texto "Seu carrinho está vazio"
- Adicionado componente ShoppingCartButton
- Incluído rota "/shopping-cart" para página  ShoppingCart
- Corrigido alguns erros encontrados pelo linter
- Criado e adicionado ícone para componente ShoppingCartButton
> [Grupo 25] Requisito 03

- package.json
- src/App.js
- src/components/ProductCard.js
- src/components/ProductList.js
- src/services/api.js
Atualizada minha branch local com as atualizações referentes ao requisito 3 e 4.
Desenvolvida lógica de exibir produtos a partir do texto digitado pela pessoa usuária no input no component ProductList.
Criado component ProductCard para cada produto, chamado na renderização através do map na lista de produtos retornados pela API com o termo procurado pela pessoa usuária.
> [GROUP 10] Implementando buscar produtos por termos

- src/components/InitialScreen.jsx
- src/components/SideBar.jsx
Filtro de itens carregados na tela principal através das categorias no SideBar.
> [GROUP - 18] - Filter categories

- src/App.css
- src/components/Header.jsx
- src/components/InitialScreen.jsx
- src/components/ProductList.jsx
- src/components/index.js
- Criação componente ProductList
- Criação componente Header
- Refatoração do html do componente InitialScreen
> [GROUP - 18] - Refatoração html

- src/components/Card.jsx
- src/components/Categories.jsx
- src/components/List.jsx
- src/components/SearchBar.jsx
- src/components/Shopping-cart-icon.jsx
- src/pages/ShoppingCart.jsx
- src/pages/home.jsx
- src/serviceWorker.js
- src/services/api.js
- src/setupTests.js
//somente o Hamaji pode me julgar
~boa noite~
NÃO DEM O MERGE ATÉ EU ACORDAR!!!NÃO DEM O MERGE ATÉ EU ACORDAR!!!
NÃO DEM O MERGE ATÉ EU ACORDAR!!!NÃO DEM O MERGE ATÉ EU ACORDAR!!!
NÃO DEM O MERGE ATÉ EU ACORDAR!!!NÃO DEM O MERGE ATÉ EU ACORDAR!!!
NÃO DEM O MERGE ATÉ EU ACORDAR!!!NÃO DEM O MERGE ATÉ EU ACORDAR!!!
NÃO DEM O MERGE ATÉ EU ACORDAR!!!NÃO DEM O MERGE ATÉ EU ACORDAR!!!
> [group 38] focosi na madruga

- src/App.css
- src/App.js
- src/components/ItemCategory.jsx
- src/components/ListCategory.jsx
- src/components/Loading.jsx
- src/pages/Home.jsx
PRIORIDADE 1 - Listar filtros de categoria obtidos da API na tela principal, de listagem do produto. A requisição da API para recuperar as categorias deve ser feita uma única vez após o carregamento da tela
> [ GRUPO 06 ] Criando Lista de Categorias - Requisito 04

- src/Components/ButtonCart.js
- src/Components/Search.js
- src/index.js
Criação dos cards via termo do Search para realizar a requisição na API do ML
> [Main group 8] Listagem dos produtos pelo termo retorno da API

- src/components/CategoryList/index.js
- src/pages/ProductList/index.js
**O que foi feito:**
Filtrar corretamente os produtos de uma página para exibir somente os daquela categoria.
> GRUPO 17 - Requirement 6

- src/App.js
- src/CategoryList.js
- src/ProductList.js
- src/services/api.js
Requisito 4 - listar filtros de categoria
> Listar filtros de categoria 

- .eslintrc.json
- src/services/api.js
- Melhoria no requisito 1 - implementa as requisições à API. Agora é possível pesquisar por termo, por categoria ou pelos dois.
> [GROUP 5] Acesso a API ML

- src/App.css
- src/App.js
- src/components/CategoriesList.jsx
- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/components/SearchBar.jsx
- src/pages/Home.jsx
- src/services/api.js
- Lista com filtros de categoria obtidos da API na tela principal
> [Grupo 3] - Listando categorias pela API na pagina principal

- src/App.js
- src/components/Product.js
- src/pages/ProductDetail.jsx
##O que foi feito
Adição do link que leva a outra pagina com os detalhes de cada item (conforme o item clicado)
*FALTANDO O CSS*
> Adição do link que mostra de forma detalhada ao clicar nos produtos

- src/App.js
- src/Components/ShoppingCartButton.js
- src/Header.js
- src/Pages/ShoppingCartPage.js
-Foi criada a pasta "Pages", que contém a página criada "ShoppingCartPage.js"
-Foi criado o componente "ShoppingCartButton.js" que contém o link para a pagina "ShoppingCartPage.js"
> Criaçao da pagina carrinho de compras e do botao-Requisito 3

- package-lock.json
- src/App.js
- src/components/forms/Input/index.js
- src/components/forms/Input/style.js
> [Group 13] Created input

- src/Components/Search.js
- src/Pages/Home.js
Criação do All Products List para separar no search
> Main group 8 create product list

- src/Components/CardList.js
- src/Components/CardProduct.js
- src/Components/DigiteTermo.js
- src/Components/ListAllProducts.js
- src/Components/ProductDetails.js
- src/Components/ProductNotFound.js
Enviando arquivos criados na minha branch
> [Main group 8]  Enviando Arquivos criados

- src/components/Card.jsx
- src/components/ListCards.jsx
Componentes CardProduct e ProductList
> card product e productList

- src/components/CategoriesList.jsx
- src/components/ShowProducts.jsx
- src/pages/ProductsList.jsx
- src/services/api.js
- implementada função para fazer busca utilizando apenas o id da categoria;
> [GROUP 39] Finalizado requisito 6

- src/Components/Categories.js
- src/Header.js
- src/Pages/Home.js
- Criado arquivo 'Components/Categories.js'
- Criado lógica da lista de categorias no arquivo 'Pages/Home.js
- Implementado Categories na Home
> Main group 23 listar categoria de produtos

- src/App.css
- src/Pages/Home.jsx
- src/components/CategoryItem.jsx
- src/components/CategoryList.jsx
- src/services/api.js
* Foi adicionada a Lista de Categorias
> adicionada lista de categorias

- package-lock.json
- package.json
- src/App.js
- src/Pages/Home.jsx
- src/Pages/ShopPage.jsx
- src/components/ButtonShop.jsx
- src/components/EmptyShopCar.jsx
Requisito 3
Cria um botão icone
Cria uma pagina para o carrinho de compras
Adiciona uma biblioteca para criar o icone
> Main group 30 requisito 03

- src/components/SearchBar.js
- src/pages/ShoppingCart.js
-Identação no componente ShoppingCart e adição de id e tipos para os botões do Carrinho - Requisito nº 3.
> Group 5 shopping cart

- src/Pages/Home.jsx
- src/components/Item.jsx
- src/services/api.js
Utilizei a função de buscar por produtos e chamei ela na Home para que possa listar os produtos buscados pelo usuário.
> Requisito 5: Listagem de produtos buscados

- .gitignore
- .prettierrc
- src/App.js
- src/pages/Category.jsx
Algumas refatorações, mudanças de código e correções de arquivos.
> [Group 14] - Correções de arquivos

- package-lock.json
- src/components/ShoppingCartButton/ShoppingCartButton.jsx
- src/pages/HomePage.jsx
- src/pages/ShoppingCart.jsx
- src/router.js
Implementando o botão para acesso ao carrinho de compras!!
> [Group-28] [Priority 1] [Implementation-Shopping-Cart-Button]

- src/App.js
- src/components/Categoria.js
- src/components/Categorias.js
- src/components/productListing.jsx
- src/pages/Home.js
Criada uma callback passada para a lista de categorias que quando ativada troca o status de app e passa esse status como prop para o productListing
> [Main group 36] Category selection change

- src/App.css
- src/components/ProductCard.jsx
- src/components/SearchBar.jsx
- src/pages/Home.jsx
- src/pages/ProductNotFound.jsx
[x] - Buscar por termos e receber uma listagem de produtos, com dados resumidos,
associados a esses termos
✓ Exibe todos os produtos retornados pela API, dado um determinado
filtro (50ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.923s, estimated 3s
> [GROUP-29] - Buscar por termos e receber uma listagem de produtos

- src/components/CardProduct.jsx
- src/components/ListCategory.jsx
- src/pages/Home.jsx
- src/services/api.js
> [ GRUPO 6 ] Listagem de produtos

- src/App.js
- src/components/Categoria.jsx
- src/components/ListaDeCategorias.jsx
- src/pages/ListagemDeProdutos.jsx
criei os componentes ListaDeCategorias e Categorias; fiz a logica para recuperar a requisição das categorias e renderizar isto na tela.
> Criando os componentes para renderizar a lista de categorias

- src/components/Categories.js
- src/pages/home.js
Na Home criei um state.category, uma função handleCategory que é passada para o componente categories e modifiquei a fetchAPI para levar em conta as categorias. No componente tive que criar botões para atender o pedido do Lint pois precisava do onClick criei o state.selectedCategory para pintar a tela diferenciando a categoria selecionada e criei a função selectCategory que atualiza o estado e chama a callback.
> [Group 16] add category filter

- src/App.js
- src/components/forms/Button/index.js
- src/components/forms/Button/style.js
> [Group 13]  Criado de forma generalizada o componente button

- src/App.js
- src/components/Header/index.js
- src/components/Header/style.js
- src/components/index.js
- src/style/global.js
> [Group 13] Criação do Header e GlobalCss.

- src/components/CategoryList.js
- src/components/ProductList.js
Arquivos modificados:
- components/CategoryList.js 
- components/ProductList.js
CategoryList.js:
Trocado: 
Span por label
test-dataid para dentro do input.
Tipo de input de checkbox para radio
Adicionada função handleClickCategory no onClick por props em CategoryList.
ProductList.js:
Atualizado function updateState para receber as categorias
Adicionada função handleClickCategory
> [Grupo 10] Filtrar por categoria

- src/App.js
- src/components/Loading/index.js
- src/components/Loading/style.js
- src/style/global.js
> [Group 13] Criação do componente Loading.

- src/App.js
- src/components/InitialScreen.jsx
- src/components/ProductCard.jsx
- src/components/ProductDetail.jsx
- src/components/index.js
- src/services/api.js
Criação componente ProductDetail
> [Main Group 18] Product Detail 

- src/App.js
- src/components/Card.jsx
- src/pages/ProductDetails.jsx
- src/services/api.js
Product detteile set - requisit 7
> [ Group 38 ] -  Detaile

- src/App.js
- src/pages/Category.jsx
- src/pages/Main.jsx
- src/pages/NotFound.jsx
- src/pages/ProductList.jsx
- src/services/api.js
- Adicionado lógica de estados e componentes, da qual é verificada a existencia de produtos, para então ser passado os dados por props, para que os "cards" sejam então, renderizados em tela.
- Adicionado uma lógica, da qual o componente pai (Main.jsx), possui acesso a dados e funções, das quais são passadas via props, para então serem modificadas e acionadas pelo filho (Category.jsx)
> [Group 14] Requisições 5 e 6.

- package-lock.json
Como houve alterações após o comando npm install, foi necessário: 
- criar uma branch inicial;
- fazer pull requeste;
- merge na branch: main-group-40
> mudanças no package-lock.json após o comando: npm install

- src/App.css
- src/components/ListCategories.jsx
- src/components/SearchBar.jsx
- src/components/ShoppingCartButton.jsx
- src/pages/Home.jsx
- src/pages/ShoppingCart.jsx
galera me perdoem, tive que fazer algumas mudan;as no código em geral e para conseguir fazer funcionar. Coloquei todas as funções na Home e passei elas por callback para os componentes filhos. se quiserem mudar essa configuração depois a gente faz isso juntos.
> [GROUP 29] Select category

- package-lock.json
- package.json
- src/components/InitialMessage/InitialMessage.jsx
- src/components/NotFound/NotFound.jsx
- src/components/ProductCard/ProductCard.jsx
- src/components/ProductList/ProductList.jsx
- src/components/SearchBar/SearchBar.jsx
- src/pages/HomePage.jsx
- src/services/api.js
Creating Product List, cards, and rendering logic.
> [GROUP 28] [PRIORITY 1] [REQUIREMENT 5] [CREATING PRODUCT LIST]

- src/App.js
- src/components/Home.js
- src/components/ShoppingCart.js
> Adicionado alterações de rotas

- .github/workflows/main.yml
- src/components/Cart.jsx
Adicionando botões de adicionar e remover quantidade no carrinho
> [GRUPO 21] - Requisito 10

- .github/workflows/main.yml
- README.md
- package.json
- src/components/Category.jsx
- src/pages/Home.js
Criado pasta **src/components**, arquivo **Category.jsx.**. E componente **Category**, o qual retorna uma lista não ordenada em uma tag **aside**.
Foi adicionado um **_id_** que corresponde ao **_id_** utilizado na requisição de uma categoria especifica na **API** para utilizar o filtro.
> Main group 40 requisito 4

- .github/workflows/main.yml
- src/components/CategorieFilter.jsx
- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/components/SearchBar.jsx
- src/pages/Home.jsx
Requisitos 4, 5 e 6 funcionando.
Quebrei o código em componentes para ficar mais clara a leitura.
Apresenta problemas de Lint p/ PropsValidation
> requisito6 e divisao de components

- src/App.js
- src/components/ProductList.jsx
- src/pages/ProductDetails.jsx
- src/style/productList.css
Fiz apenas a lógica básica, sem estilização. É necessário melhorar para ficar apresentável.
Ainda não fiz o código pegar as "especificações técnicas" descritas na imagem ilustrativa do requisito para montar ao lado da imagem, mas de qualquer forma não é algo necessário para o momento. Adicionalmente, utilizei a thumbnail como imagem principal do produto por enquanto.
✓ Clicar no card produto leva à página com seus detalhes
> [Grupo 35] Requisito 07 - Adição da funcionalidade de clique para abrir a página de mais detalhes

- src/App.js
- src/pages/CategoriesList.js
- src/pages/Home.js
##O que foi feito:
Função para buscar pela barra de categorias
> [Grupo 15]Busca pela barra de categorias

- .github/workflows/main.yml
- src/Components/CardList.js
- src/Components/CardProduct.js
- src/Components/DigiteTermo.js
- src/Components/ListAllProducts.js
- src/Components/ProductDetails.js
- src/Components/Search.js
- src/Pages/Home.js
Refatoração
Correção requisito 5
> Resolved Lint

- .github/workflows/main.yml
- src/App.css
- src/components/CategoriesList.jsx
- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/components/SearchBar.jsx
- src/components/index.jsx
- src/pages/Home.jsx
- src/services/api.js
- Criação da listagem de produtos utilizando a ação de um botão, tendo como parâmetros a frase digitada
P.S.: Foi suado! hehehe
> [Grupo 3] Lista de produtos

- .github/workflows/main.yml
- package-lock.json
atualizei o arquivo ./github/workflows/main.yml, conforme orientação do Hamaji no Slack
> [GRUPO 9] Meu título

- src/components/ProductCard/ProductCard.css
- src/components/ProductCard/index.js
- src/components/ProductList/index.js
- src/pages/Home/Home.css
Adicionando o Component Product Card, citado no requisito 05
> [GRUPO 24] Complementando o Requisito 05 - Component Product Card

- src/App.js
- src/components/Icons/index.js
- src/components/index.js
> [Group 13] criação dos ícones

- .github/workflows/main.yml
- src/App.css
- src/App.js
- src/components/CardProduct.jsx
- src/components/ItemCategory.jsx
- src/components/ListCategory.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
> requisito 6 - filtrando produtos buscados

- src/components/ProductCard.jsx
- src/pages/Home.jsx
Atualiza arquivos para resolução de conflitos
> [Grupo 4] Main group 4 atualiza arquivos

- src/App.js
- src/components/Card/index.js
- src/pages/ProductDetails/index.js
- src/pages/ProductList/index.js
O que foi feito:
-Clicar no card produto leva à página com seus detalhes
> GRUPO 17 - Requerimento 7

- .github/workflows/main.yml
- src/App.js
- src/components/ProductCard.js
- src/components/ProductDetails.js
- src/components/ProductList.js
- src/components/ProductSpec.js
Criado component ProductDetails que apresenta informações específicas do produto clicado pela pessoa usuária e faz uso do component ProductSpec para renderizar a lista de especificações técnicas daquele determinado produto.
As informações são passadas pela props do component Link do react-router-dom, que recebe como valor a prop product, referente ao objeto daquele produto renderizado no card. Ela é recuperada no component ProductDetails através de this.props.location.
> Main group 10 pagina detalhes produto

- .github/workflows/main.yml
> [GRUPO 17] - Fix GitHub Evaluator

- src/App.css
- src/components/CardProduct.jsx
- src/components/Loading.jsx
- src/pages/Cart.jsx
- src/pages/Home.jsx
##Commit inicial de adição de CSS na página do carrinho
> [Group 6]Main group 6 css

- .github/workflows/main.yml
- src/App.js
- src/components/CategoryList.js
- src/components/ItemCategory.js
- src/components/ProductsList.js
- src/pages/Products.js
- Implementação do requisito 6
> [Grupo 25] Requisito 6

- .github/workflows/main.yml
- package-lock.json
- package.json
- src/components/FilteredCards.js
- src/components/FilteredProductsList.js
- src/components/IndividualCard.js
- src/components/SearchBar.js
- src/pages/ProductsList.js
- src/services/api.js
Foram implementadas as funções dos botões de pesquisa de modo que consigam ser gerados os cards
> [Main group 5] lista de cards primeiro filtro por query

- src/App.css
- src/components/Header.jsx
- redução do tamanho do carrinho de compras
> [Main-Group-18] Inicio CSS

- .github/workflows/main.yml
- src/components/searchBar.jsx
Adicionando componentDidMount | Corrigind main.yml para resolver bug do avaliador
> Requisito 6 - Adicionando componentDidMount | Corrigind main.yml

- src/App.js
- src/components/ProductCard.jsx
- src/pages/ProductDetails.jsx
Bora fazer aquele review como quem não quer nada bora?
> [Main Group 29] Cria página de detalhamento do produto

- src/App.css
- src/components/Cart.jsx
- src/components/FormDetail.jsx
- src/components/ProductDetails.jsx
Adicionando formulário de avaliação do produto
> [GRUPO 21] - Requisito 11

- .github/workflows/main.yml
- src/components/CategoryList.css
- src/components/CategoryList.jsx
- src/components/SearchBar.css
- src/components/SearchBar.jsx
- src/pages/listagem.css
- src/pages/listagem.jsx
- src/services/api.js
Criada a listagem de produtos. Fazer a exibição resumida do produto  com título, foto e preço ao fazer requisição à API do Mercado Livre enviando os termos.
> [GRUPO 22]  BUSCAR POR TERMOS E RECEBER UMA LISTAGEM DE PRODUTOS, COM DADOS RESUMIDOS

- src/App.js
- src/components/Icons/index.js
- src/components/index.js
- src/views/SearchInput/index.js
- src/views/SearchInput/style.js
> [Group 13] Criando o primeiro view part 1.

- .github/workflows/main.yml
- src/pages/ProductDetail.jsx
- src/pages/ProductsList.jsx
* Adicionando formulário para avaliação do produto no arquivo ProductDetails
> [GRUPO 39] Requisito 11 - AVALIAR E COMENTAR ACERCA DE UM PRODUTO EM SUA TELA DE EXIBIÇÃO DETALHADA

- src/App.js
- src/Components/CategoryList.jsx
- src/Components/ProductCard.jsx
- src/Components/ReturnButton.jsx
- src/Components/ShoppingCartButton.jsx
- src/Pages/ProductDetails.jsx
- src/Pages/ShoppingCart.jsx
> [GRUPO 19] Requisito 7 - Product Details.

- src/App.js
- src/components/categoryList.jsx
- src/components/productCard.jsx
- src/pages/productDetail.jsx
- src/services/api.js
> Requirement 7 :rocket:

- src/App.css
- src/components/Kart.jsx
- src/components/KartItens.jsx
- src/components/ProductCard.jsx
- src/components/ProductDetail.jsx
- src/components/ProductList.jsx
- src/services/storageServices.js
- Implementação do botão na tela de detalhes do produto
> [Main group 18] Botão adicionar ao carrinho | Detalhes do produto

- src/components/Itens.jsx
- src/components/Kart.jsx
- src/components/KartItens.jsx
- src/components/ProductCard.jsx
- src/components/ProductDetail.jsx
- src/components/ProductList.jsx
- src/services/storageServices.js
- Adicionando item ao carrinho pela tela inicial
> [GROUP - 18] Add product cart local storage

- src/components/CategoryList.jsx
- src/components/SearchBar.jsx
- src/pages/carrinho.jsx
- src/pages/listagem.jsx
> [GROUP 22] requisito 06

- src/App.js
- src/services/api.js
> Lint corrections

- src/components/Card/index.js
- src/components/CartItem/index.js
- src/components/CategoryList/index.js
- src/pages/ProductDetails/index.js
- src/pages/ProductList/index.js
- src/pages/ShoppingCart/index.js
- src/services/cartApi.js
> [GRUPO 17] - Requisito 8

- src/App.js
- src/components/CartItem.js
- src/components/productListing.jsx
- src/pages/CartList.js
- src/pages/ProductDetail.jsx
- src/services/cartAPI.js
O que foi feito:
Uma CartAPI com funções para adicionar itens ao carrinho e ler o carrinho.
Uma page CartList que retorna os itens adicionados da página de detalhes de cada produto e a respectiva quantidade de cada um.
> [Grupo 36] add to cart from details page of each product.

- src/components/GoToShoppingCart.js
- src/components/SearchBar.js
- src/services/api.js
-Criação de componente para ir para o carrinho de compras;
-Implementação deste componente em SearchBar;
-Correção para o ESLint (falta de ponto e vírgula) no arquivo api.js
> Group5 go to shopping cart

- package-lock.json
- src/App.css
- src/App.js
- src/components/Card.jsx
- src/components/Categories.js
- src/components/ProductDetail.jsx
- src/pages/Home.jsx
> implementaçao produc detais e link router datails

- src/App.js
- src/components/ProductAttributes.js
- src/components/ProductCard.js
- src/pages/ProductDetails.js
- Criado página de detalhes do produto selecionado
- Passagem de props via Link, recuperado em `this.props.location.state.product`
- Criado componente para os atributos (especificações técnicas) do produto
- Adicionado rota no App
- Adicionado link de detalhes no ProducCard
> [GRUPO 25] - Requisito 07

- src/components/CartItem/index.js
- src/pages/ProductDetails/index.js
- src/pages/ShoppingCart/index.js
- src/services/cartApi.js
-[x]- Criado o componente CartItem
-[x]- Implementacao da funcionalidade que adiciona um produto ao carrinho a partir da sua tela de detalhes.
> Main group 17 requirement 9

- src/components/ProductCard.js
- src/components/ProductDetails.js
- src/components/ProductList.js
- src/components/ShoppingCart.js
- src/services/utils.js
Depois de muito quebrar a cabeça tentando usar o Link, fomos salvos pelo mestre Jedi Thay que nos lembrou da existência do localStorage.
Criado arquivo utils com funcionalidades para armazenar produtos no LocalStorage tanto adicionados pela página de listagem quanto pela página de detalhes de um produto e depois uma função que recupera essa informação do localStorage para que seja armazenada no state do Carrinho de compras e renderize as informações dos produtos adicionados ao carrinho.
> [GROUP 10] criada funcionalidade adicionar produtos ao carrinho

- src/App.css
- src/App.js
- src/components/CategoriesList.jsx
- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/components/SearchBar.jsx
- src/components/index.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
-  Visualizar a exibição detalhada do produto com nome do produto, imagem, preço e especificação técnica.
> [Grupo 3] Detalhes do produto

- src/App.js
- src/components/ProductReview.jsx
- src/components/RatingForm.jsx
- src/components/SearchBar.jsx
- src/pages/ProductDetails.jsx
Adicionado um formulario para o usuario preencher com seu email, nota e opcionalmente um comentario.
Esse formulario fica salvo no localStorage.
> [Group 35] Requisito 11

- src/services/lsapi.js
Iniciando a implementação de um api para o local storage.
Considerando os objetos que irão transitar entre as páginas.
Selected Product
Shopping Cart List
> [GRUPO 24] Criando LocalStorage API

- src/App.css
- src/App.js
- src/components/CategorieFilter.jsx
- src/components/EmptyProductList.jsx
- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/components/ShoppingCartButton.jsx
- src/pages/Home.jsx
- src/pages/ProductDetail.jsx
- src/pages/ShoppingCart.jsx
- src/services/api.js
Corrige Bug da busca por categoria;
Requisito 7;
Um pouco de CSS;
> [Grupo 4] Requisito7 e correção de bug da categoria

- src/components/ProductCard/index.js
- src/pages/ProductDetail/index.js
- src/services/lsapi.js
Ajustando Requisito 07 para trabalhar com a api de local storage.
> [GRUPO 24] Ajustando Requisito 07

- src/App.js
- src/components/States.jsx
- src/pages/Payment.jsx
- src/pages/ShoppingCart.jsx
Code review parcial, para dar continuidade precisa estar atualizado os requisitos anteriores.
> [Group 38]  Requisito 12 - payment

- src/components/CommentForm.js
- src/components/CommentsList.js
- src/pages/ProductDetail.js
- src/pages/ProductList.js
**PRIORIDADE 3** - Adicionar formulário ao produto, em sua exibição detalhada, para permitir adicionar avaliações com nota de 1 a 5 estrelas e comentários (o comentário deve ser opcional, sendo possível enviar apenas a nota). Exibir a lista de avaliações já feitas. Se quem usa sai e volta da tela, a nota e as avaliações não devem ser apagadas (veja os detalhes no card).
Observações técnicas
Avaliações positivas de um produto contribuem para boas vendas e nos dão insumos para, no tempo, destacarmos os produtos melhores e fazermos anúncios direcionados. Produtos ruins, de forma análoga, podem eventualmente ser penalizados por avaliações ruins.
Adicione um campo de texto para que a pessoa que utiliza a aplicação possa escrever algo sobre o produto.
Adicione o atributo `data-testid` com o …
> [Group 11] Requisito 11 - Seção de Comentários

- src/components/ProductsList.js
**O que foi feito:**
Retirando o `componentDidMount` do ProductList.js, conseguimos que o teste 4 não tropece na chamada da função que ele está tentando testar. Porém, ao fazer isso, o requisito 6 deixa de passar (o que deduzimos que era o esperado pois na verdade ainda não trabalhamos no requisito 6).
> [Grupo 20] Fazendo os requisitos 4 e 5 passarem simultaneamente

- src/components/CartItem.jsx
- src/components/Product.jsx
- src/pages/ProductDetail.jsx
- src/pages/ShoppingCart.jsx
- adicionadas funções **sumItem** e **subtractItem** para adicionar e remover itens do carrinho;
- removida soma dos valores das funções que adicionavam itens ao localStorage por problemas na hora da subtração;
> [GROUP 39] requisito10 v4

- src/App.css
- src/Components/FiltersCategory.jsx
Fiz um CSS simples só pra ficar mais organizado pra montar a página
Se quiserem melhorar fiquem a vontade meninos, se não depois eu mecho e deixo "mais melhor" kkkk
> Add CSS style in Side Bar Categorys

- src/components/ShoppingCart.js
Foi feito no componente ShoppingCart.js funções que adicionavam um estado para cada produto. Assim, depois, devido a problemas do lint, não conseguimos buscar através dos próprios this.state. Então, utilizamos o Object.entries no this.state, seguido de um Find dentro do Object.entries para filtrar o resultado do id correspondente. Devido a assincronidade, enfrentamos problemas ao acessar o resultado. Logo, foi feito uma condicional ternária para definir um valor padrão para o result caso tivesse um valor undefnied.
> [Grupo 10] Requisito 10 -> Quantidade do produtos na aba ShoppingCart.js

- src/App.js
- src/components/Categories.js
- src/components/Product.js
- src/components/ProductList.js
- src/pages/Details.js
- src/pages/home.js
- src/services/api.js
**Antes de ler a lógica da uma olhada no App.js e  Details.js** 
Lígica: passar os elementos SearchKey e Category, por meio das rotas, para a página details, pra que seja possível fazer a requisição à API com os mesmos parametros que foi feito na página Home, tambem é passado via route o ID do produto clicado. Com o retorno da API é possível usar a high order function FIND pra encontrar o produto com o mesmo ID passado pela rota, quando encontrado, as informações desse elemento são geradas na pagina details
> [GROUP 16] Detail page 7 3t

- src/components/CartItem/index.js
- src/pages/ShoppingCart/index.js
- src/services/cartApi.js
O que foi feito:
Adicionar lista de produtos ao carrinho, com valor total ao final. Criar botões (-) e (+) para cada produto do carrinho, permitindo alterar a quantidade desejada de cada produto. A quantidade não pode ser negativa. Criar também botão (X) para remover produtos do carrinho e botão para finalizar a compra.
> Grupo 17 - Requerimento 10

- package-lock.json
- package.json
- src/components/RatingForm.js
- src/pages/ProductDetails.js
- src/services/ratingAPI.js
-Criado API para manipular avaliação dos produtos;
-Criado formulário para avaliação do produto;
-Atualizado página ProductDetails com a adição do formulário;
> [Grupo 25] - Requisito 11

- src/components/Product.jsx
- src/pages/ProductDetail.jsx
- src/pages/ShoppingCart.jsx
- adicionas as funções:
a) roundNumber: recebe um string, chama a função **removeZero** e retorna um número com as duas últimas casas após a vírgula (caso o string possua esses dois números após a vírgula);
b) removeZero: recebe um string e verifica se o primeiro item do string é igual a 0. Se for, ele devolve o string. Caso contrário, ele chama a função **removeLastItem** três vezes, retornando, por fim, um string;
c) removeLastItem: recebe um string, verifica se o último item do string é igual a 0 ou igual à '.', e caso positivo, remove o último caractere do string, devolvendo o string; em caso contrário, simplesmente devolve o string;
> [GROUP 39] Adicionada funções para somar e subtrair itens

- src/components/Evaluation.jsx
- src/pages/Details.jsx
- Adicionado campo de texto na area de detalhes.
> [Group 14] - Requisito 11

- src/components/ShoppingCart.js
O problema em que poderíamos reduzir o carrinho a 0 e consequentemente números negativos, foi resolvida.
> [Grupo 10] problema das quantidade dos carrinhos resolvida

- src/components/CartItem.jsx
- src/pages/ShoppingCart.jsx
- Adicionado botão na página do carrinho para remover item do carrinho;
> Adicionado botão para remover item do carrinho

- src/components/FormRating.jsx
- src/components/ProductCard.jsx
- src/components/ProductDetail.jsx
Componetização  FormRating.jsx
> [Main group 18] - Rating Form

- src/components/Product.js
> colocando null

- src/components/ProductList.jsx
Adicionei um paragrafo com o texto frete grátis aos produtos que possuem frete grátis.
> [Grupo 35] Requisito 15

- src/components/ProductDetails.js
- src/components/ProductEvaluationForm.js
adicionando feature de formulário de avaliação de produto.
> Main group 10 form product details

- src/components/ProductCard/index.js
- src/components/ProductList/index.js
- src/components/SearchBar/index.js
- src/components/ShoppingCartList/index.js
- src/pages/Home/index.js
- src/pages/ShoppingCart/index.js
1. Implementação do botão para incluir produto no carrinho de compras a partir da lista de produtos;
1. Implementação da página ShoppingCart pra exibir os produtos adicionados ao carrinho;
1. Arquivos alterados:
* src/components/ProductCard/index.js
* src/components/ProductList/index.js
* src/components/SearchBar/index.js
* src/components/ShoppingCartList/index.js
* src/pages/Home/index.js
* src/pages/ShoppingCart/index.js
> [Grupo 24] Requisito 08

- src/App.js
- src/components/Header/style.js
- src/components/Icons/index.js
- src/components/forms/Button/style.js
- src/components/forms/Input/index.js
- src/components/forms/Input/style.js
- src/components/index.js
- src/pages/Home/index.js
- src/pages/Home/style.js
- src/style/global.js
- src/style/reset.js
- src/views/SearchInput/index.js
- src/views/SearchInput/style.js
> [Group 13] Main group 13 create page home

- src/components/ProductDetail.jsx
<li> Link carrinho de compras no ProductDetails
> [Main-group-18] Requisito 9 dm

- .editorconfig
- .prettierrc
- src/App.js
- src/components/Icons/index.js
- src/views/AmountControllers/index.js
- src/views/AmountControllers/style.js
- src/views/index.js
Este componente sera usado na montagem da página de detalhe do produto e nos cards de produto na página carrinho de compras.
> [Group 13] Main group 13 view amount controllers

- src/App.js
- src/components/Icons/index.js
- src/views/RatingStar/index.js
- src/views/RatingStar/style.js
- src/views/index.js
Realizada a criação da view rating star para ser usada na página detalhe de produtos e cards de avaliações.
> [Group 13] Main group 13 view rating star

- src/App.js
- src/pages/Cart.jsx
- src/pages/Checkout.jsx
- Formulário criado a partir do arquivo `Checkout.jsx`.
- Criado uma rota para o formulário em `App.js`.
- Link do formulário adicionado a página de carrinho `Cart.jsx`.
> [Group 14] Requisito 12

- src/components/ProductAttributes.js
- src/components/ShowCartItems.js
- src/pages/ProductDetails.js
- src/pages/ShoppingCart.js
- src/services/localStorageHandler.js
- Implementação de lógica para adicionar produto da página de detalhes para o carrinho de compras.
> [Grupo 25] Requisito 9

- src/Components/ListCardsProduts.js
> Nova versao mais do que atualizada

- src/App.js
- src/components/CartItem.jsx
- src/pages/Checkout.jsx
- src/pages/ProductDetail.jsx
- src/pages/ShoppingCart.jsx
* Tela de checkout para finalizar a compra dos produtos
* Formulário para preencher os dados do comprador
* Resumo dos produtos adicionados ao carrinho de compras
* Forma de pagamento
> [GRUPO 39] Requisito 12 - FINALIZAR COMPRA, VENDO UM RESUMO DELA, PREENCHENDO OS MEUS DADOS E ESCOLHENDO A FORMA DE PAGAMENTO

- src/App.css
- src/Components/FiltersCategory.jsx
- src/services/api.js
> Correction in logic call API

- src/components/CartIcon.jsx
- src/components/Product.jsx
- src/components/ShowProducts.jsx
- src/pages/ProductDetail.jsx
- src/pages/ProductsList.jsx
- implementado componente **CartIcon** que será renderizado nas páginas **ProductsList** e **ProductDetail**;
- feitas alterações no código de **Product**, passando a função **addItemToLocalStorage** para a página **ProductsList**;
- incluído o estado **quantityChanged** nas páginas **ProductsList** e **ProductDetail** para re-renderizar o componente **CartIcon** quando o estado mencionado é alterado; o valor do estado é um _boolean_;
- implementada função nas páginas para alterar o estado do componente quando um item é adicionado ao local storage.
> Main group 39 requisito 13

- src/Components/AddToCartButton.js
- src/Components/ProductCard.js
- Criado componente do botão
- Implementado botão no componente ProductCard
> implementando botao de adicionar ao carrinho de compras

- src/components/CartItem.js
- src/components/Product.js
- src/pages/Cart.js
- src/services/addToCart.js
product.js 
chamada de addtoCart com category e search key
botão addToCart
addToCart.js
addToCart agora grava category e searchkey no localstorage
Cart.js
CartItem.js
> [Group 16] add cart finally work

- src/components/ProductDetail.jsx
- src/components/Rating.jsx
- src/components/RatingAndComment.jsx
Implementação de campo de comentários e radio buttom para avaliador.
A logio do radion buttom ainda não está funcionando.
> requisito11

- src/components/CardProduct.jsx
- src/components/ItemCart.jsx
- src/pages/Cart.jsx
- src/pages/ProductDetails.jsx
> [GRUPO 6] tentando colocar itens no localStorage

- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
> Requisitos 8 e 9 [Main-group-3]

- src/components/ListCategory.js
- src/pages/ProductsList.js
Implementadas as funções de pesquisar somente por categoria e também filtrar os produtos já pesquisados usando o id de uma categoria
> Main group 5 fazendo pesquisa por categoria

- src/components/ButtonAddCart.jsx
- src/components/ProductList.jsx
- src/components/SearchBar.jsx
- src/components/ShoppingCart.jsx
> [GRUPO 35] Adicionar produtos a partir da tela de listagem de produtos

- src/App.css
- src/Pages/ProductDetails.js
Realizei algumas melhorias no código e nas telas
> [Main-Group-8] Estilizando o restante das telas, adicionando algumas melhorias

- src/App.css
- src/App.js
- src/Components/ButtonCart.js
- src/Components/CardsRenderList.js
- src/Components/CategorieCard.js
- src/Components/DigiteTermo.js
- src/Components/ListCardsProduts.js
- src/Components/ProductNotFound.js
- src/Pages/Cart.js
- src/Pages/Home.css
- src/Pages/Home.js
- src/Pages/ProductDetails.js
> [Main-Group-8] Correçoes no lint

- src/Components/CardsRenderList.js
- src/Components/CategorieCard.js
- src/Components/ListCardsProduts.js
- src/Pages/Home.js
- src/index.js
- src/services/api.js
Mais algumas correções do lint
> Correçoes no lint

- src/components/CartIcon.jsx
- src/components/CartItem.jsx
- src/components/CategoriesList.jsx
- src/components/Product.jsx
- src/components/ShowProducts.jsx
- src/pages/ProductDetail.jsx
- src/pages/ShoppingCart.jsx
* Adicionado import do propTypes
* Inserido validação das props onde necessário
> [GRUPO 39] - Adicionando props para validação

- src/components/DetailsForm.js
- src/components/Rating.js
- src/pages/Details.js
no arquivo CartItem.js mudei o porptypes quantity de PropTypes.string.isRequired pra PropTypes.number.isRequired, esse era o motivo do erro, o arquivo pedia uma string como elemento do quantity mas na verdade recebia um numero
tambem adicionaei localStorage e um forms na pagina Detail, sendo possivel adicionar avaliações para cada produto de forma independente que continuarão lá se a pagina for recarregada e o usuario voltar para o mesmo produto
> Main group 16 evaluate form product details 11 2

- src/Components/ButtonCart.js
- src/Components/CardsRenderList.js
- src/Components/CategorieCard.js
- src/Components/ListCardsProduts.js
- src/Pages/Cart.js
- src/Pages/Home.js
- src/Pages/ProductDetails.js
- src/index.js
Mais algumas correções de lint
> [Main-Group-8] Requisito7 details

- src/Components/CardsRenderList.js
- src/Components/CategorieCard.js
- src/Components/ListCardsProduts.js
- src/Pages/Cart.js
- src/Pages/Home.js
- src/Pages/ProductDetails.js
- src/index.js
Finalizando as correções do lint
> Correçao do lint - finalizando

- src/Components/CategorieCard.js
- src/Components/ListCardsProduts.js
- src/Pages/Cart.js
- src/Pages/ProductDetails.js
mais algumas, acho que da proxima vai!
> Correçao do lint - finalizando2

- src/Components/ListCardsProduts.js
- src/Pages/Cart.js
- src/Pages/ProductDetails.js
> Correçao do lint - finalizando3

- src/components/CartIcon.jsx
- src/components/Product.jsx
- src/components/ShowProducts.jsx
- src/pages/ProductDetail.jsx
- src/pages/ProductsList.jsx
- src/pages/ShoppingCart.jsx
- criadas duas funções no componente **Product**:
a) uma para renderizar um componente com frete grátis; a renderização difere se o valor passado para função é _false_ ou _true_; a única diferença é um atributo que é adicionado ao span para ser reconhecido pelo avaliador;
b) outra função apenas para retornar "Sim" e "Não" de acordo com o valor booleano do frete, "Sim" em caso de _true_ e "Não" para _false_;
- criada função na página **ProductDetail** para implementar frete grátis;
> [GROUP 39] coitado do requisito 15

- src/components/CartIcon.jsx
- src/components/Product.jsx
- src/components/ShowProducts.jsx
- src/pages/ProductDetail.jsx
- src/pages/ProductsList.jsx
- src/pages/ShoppingCart.jsx
- implementado no componente **Product** um atributo chamado _available_quantity_ no primeiro _span_ com a quantidade disponível do produto;
- implementa na função **addItemToLocalStorage** uma nova chave e valor para conter a quantidade disponível do produto e uma condicional para só aumentar o número do produto de acordo com a quantidade disponível;
- adicionada na função **sumItem** da página **ShoppingCart** condicional para aumentar o número do produto no carrinho de acordo com a quantidade disponível em estoque;
> Requisito 14 MATADO NO PEITO

- src/Components/ListCardsProduts.js
- src/Pages/ProductDetails.js
Nãaao aguento mais corrigir lintttttttt
> Correçao do lint - finalizando4

- src/Components/ListCardsProduts.js
> Correçao do lint - finalizando5

- src/Components/ListCardsProduts.js
> Correçao do lint - Acho que agora vai

- src/components/ProductCard.js
- src/components/ShowCartItems.js
- src/pages/ProductDetails.js
- src/pages/ShoppingCart.js
- Resolvido conflito de lógicas de manipulação dos ítens do carrinho entre os requisitos 8 e 9 utilizando as funções do handleLocalStorage.js para ambos os requisitos.
> [Grupo 25] Resolução de conflito entre requisitos 8 e 9

- .prettierrc
- src/App.js
- src/components/CheckoutForm.js
- src/pages/Cart.js
- src/pages/Checkout.js
- src/pages/home.js
feito req 12, corrigido conflitos entre o cart.js
> [GROUP 16] Finish buy 12

- package-lock.json
- package.json
- src/App.css
- src/App.js
- src/components/CartItem.js
- src/components/Categoria.js
- src/components/Categorias.js
- src/components/Product.js
- src/components/Products.js
- src/components/buttonsCart.jsx
- src/pages/CartList.js
- src/pages/Home.js
- src/pages/ProductDetail.jsx
- src/services/cartAPI.js
Botão de + e - no carrinho que está funcionando visualmente mas não consegui fazer passar nos testes
algumas correções do lint (falta so validar as props agora)
> [GRUPO - 36] Requisito 10 + alguns error lint

- src/components/CardProduct/index.js
- src/components/CardProduct/style.js
- src/components/Header/index.js
- src/components/Icons/index.js
- src/components/Loading/index.js
- src/components/Loading/style.js
- src/components/forms/Button/index.js
- src/components/index.js
- src/pages/Home/index.js
- src/pages/Home/style.js
- src/style/global.js
- src/views/RatingStar/index.js
- src/views/SearchInput/index.js
- src/views/SearchInput/style.js
- src/views/SideBar/index.js
- src/views/SideBar/style.js
> [Group 13] Requisito 4

- src/Components/FiltersCategory.jsx
"Requisito 4 estava dando erro e não passava no aváliador.
Erro: Retirei atributo data-testing do elemento <div>,
e coloquei a linha de código do .bind após o super().
> :bug: Removing data-testing from the div element

- src/pages/ProductDetail.jsx
Acrescentei o botão para levar ao carrinho de compras , agora todos os testes até o 9 estão ok !
> [GRUPO 4] requisito 9 passando

- .gitignore
- package-lock.json
- src/components/CardDetailsForm/index.js
- src/components/CardDetailsForm/styles.js
- src/pages/CardDetails/index.js
- src/pages/CardDetails/styles.js
implementei o formulario de avaliação dentro de CardDetails
> [Grupo 12] Main group 12 form card details

- src/components/CartItem.jsx
- src/components/Product.css
- src/components/Product.jsx
- src/components/ShowProducts.jsx
- src/pages/Checkout.jsx
- src/pages/ProductDetail.jsx
- src/pages/ProductsList.jsx
- src/pages/ShoppingCart.jsx
> Main group 39 safado do eslint

- src/pages/ProductsList.jsx
- implementada função na página **Products List** para ordenar os produtos por maior e menor preço;
- implementado seletor na página para chamar a função;
> [GROUP 39] Requisito 18

- src/components/Product.css
- src/components/Product.jsx
- src/pages/ProductsList.jsx
- adicionada funcionalidade na função **addItemToLocalStorage** que muda a classe do componente selecionado;
- adicionada função **className** no componente **Product** que verifica se o item existe no armazenamento local, retornando o nome da classe do item de acordo com a existência do item no armazenamento local ou não;
- adicionado css no **Product.css** para o item selecionado, alterando a borda dos itens selecionados para vermelho, dando um destaque;
> [GROUP 39] item selecionado

- src/components/CartItem.jsx
- src/components/Product.css
- src/components/Product.jsx
- src/components/ShowProducts.jsx
- src/pages/Checkout.jsx
- src/pages/ProductDetail.jsx
- src/pages/ProductsList.jsx
- src/pages/ShoppingCart.jsx
- adicionadas funções na página **ProductDetail** que permite manipular a quantidade do item no carrinho;
- incluídos botões na página para fazer a manipulação da quantidade do item no carrinho;
> [GROUP 39] requisito 22

- src/components/CartItem.jsx
- src/components/Product.css
- src/components/Product.jsx
- src/components/ShowProducts.jsx
- src/pages/Checkout.jsx
- src/pages/ProductDetail.jsx
- src/pages/ProductsList.jsx
- src/pages/ShoppingCart.jsx
> [GROUP 39] eslint again

- src/components/Evaluation.js
- src/pages/ProductDetails.js
> Main group 31 evaluation

- .github/workflows/main.yml
- src/components/ProductList.js
- src/pages/ProductDetails.js
- src/pages/ShoppingCartPage.js
- src/services/api.js
~~**Alterações em:**
- ProductDetails
-ShoppingCartPage
-main.yml (_correções pedidos pela trybe_)
> Main group 31 adicionar ao carrinho em detalhes

- src/Pages/Cart.js
##O que há de novo?
Faz o pull e verás!
> Atualizaçao: Refatoraçao e Estilizaçao

- src/App.js
- src/components/ProductList.jsx
- src/components/ShoppingCart.jsx
- src/pages/Checkout.jsx
Adicionado um botão dentro do shopping cart que leva para a página do checkout.
Os itens que estão dentro do carrinho são renderizados na pagina.
É exibido o valor atualizado os itens (Preço do item vezes a quantidade do mesmo item), também é exibido o preço total do carrinho.
Foi adicionado um campo para o usuario prencheer seus dados, juntamente com o campo de forma de pagamento.
Por ultimo foi adicionado um botão que remove os itens do carrinho do local Storage e retorna para a página inicial.
> [Grupo 35] Requisito 12

- .github/workflows/main.yml
- README.md
- package.json
- src/components/Evaluation.jsx
- src/components/ProductCard.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
- src/services/api.js
- Jessica e eu começamos a fazer o requisito 10, está faltando alguns detalhes para corrigir
- Criação de um formulário para a permitir adicionar avaliações com nota de 1 a 5 e comentários
> [Grupo 3] Requisitos 10 e 11

- src/App.js
- src/components/Icons/index.js
- src/components/forms/Button/style.js
- src/pages/ProductDetails/index.js
- src/pages/ProductDetails/style.js
- src/style/global.js
- src/views/AmountControllers/style.js
- src/views/RatingStar/style.js
- src/views/SideBar/style.js
> [group 13] create page details

- src/components/BuyerInfo.jsx
- src/components/Itens.jsx
- src/components/Kart.jsx
- src/components/KartItens.jsx
<li>Falha ao alterar a quantidade tela não reinderizava, apenas carregava os dados na local storage.
<li>Adicionei a função para calcular total de Itens.
<li>Implementei a lógica para remover itens do carrinho.
<li>Adicionei Link para a tela de pagamento.
<li>Correção da lógica de exibição da mensagem de carrinho vazio.
> [Main-group-18] kart adjustment

- src/pages/CardDetails/index.js
- src/pages/ShoppingCart/index.js
adicionamos a a opção de adicionar produto ao carrinho de compra na tela de details
> [Grupo 12] Main group 12 add product off details

- src/pages/ProductDetails.js
> [GROUP 29] Add product from details

- src/components/CardProduct.jsx
- src/components/ItemCart.jsx
- src/pages/Home.jsx
> [GRUPO 6] colocando limite de quantidade no carrinho

- src/components/ButtonCart/index.jsx
- src/components/CartItem/index.jsx
- src/components/ProductList/index.jsx
- src/components/SearchPlusCart/index.jsx
- src/components/index.js
- src/pages/Cart/index.jsx
- src/pages/Details/index.jsx
- src/pages/Home/index.jsx
- Foi adicionado ao `session storage`, a chave `totalQuantity`, que faz a soma de todas as quantidades de produtos adicionadas ao carrinho e atualiza em tempo real.
- Ao adicionar o produto na `session storage` em `ButtonCart`, foi passado mais um objeto, do qual, quando é chegado na quantidade máxima, seu botão de adição desabilita.
- Foi pego a informação através da API no ML se possui frete grátis, caso sim, ele é passado via props, tanto para `CategoryList`, quanto para `Details`.
> [Group 14] - Todos requisitos bonus

- src/App.js
- src/components/Checkout.js
- src/components/ShoppingCart.js
- src/components/checkout/BuyerInformation.js
- src/components/checkout/PaymentMethod.js
- src/components/checkout/ReviewProducts.js
Adicionada a funcionalidade, alteradas algumas funções na lógica do Shopping Cart mas nada muito impactante.
E Pronto pra review.
- Commitando na sexta sem ser na main! Mas que Milagre
> [Grupo 10] finalizar compra

- src/App.js
- src/__tests__/requirement8.test.js
- src/components/ProductCard.js
- src/components/ProductCartItems.js
- src/components/ProductCartList.js
- src/components/ShoppingCart.js
- src/pages/Home.js
- src/pages/ProductsList.js
> [Main-Group-32] -  Requisito 8

- src/App.js
- src/components/SearchBar.jsx
- src/pages/productDetails.jsx
##O que foi feito
Implementação do link para pagina com detalhes do produto clicado.
> Main group 22 exibicao resumida de produto

- src/App.js
- src/components/CategoriesList.js
- src/components/Home.jsx
- src/components/ProductsList.js
- src/services/api.js
-Mudanças em API.js
-Criação da página Home que agora renderiza CategoriesList e ProductsList
-Home é onde se encontra a barra de busca
-ProductsList agr recebe as props por home
-CategoriesList recebe as props por home
> [group 20]Requisito 6

- src/App.css
- src/components/Footer.js
- src/pages/ProductDetails.js
- src/pages/ProductsList.js
- src/pages/ShoppingCart.js
o que foi feito? 
foi criado um rodapé padrão para todos as paginas
> group5 rodape

- public/index.html
- src/pages/ProductsList.css
* configuração de responsividade para iphone e ipad.
> [Group-39] - Requisito 17 layout Responsivo

- src/components/Card/index.js
- src/pages/ProductDetails/index.js
**O que foi feito:**
Adicionado um elemento que mostre essa informação para cada produto que possua frete grátis na tela de listagem e na tela de detalhes.
> Grupo 17 - Requisito 15

- .github/workflows/main.yml
- package.json
- src/App.css
- src/Components/FiltersCategory.jsx
- src/Components/Header.jsx
- src/Components/Home.jsx
- src/services/api.js
> Filter by category

- src/pages/ProductDetails.jsx
✓ Adiciona um produto ao carrinho da sua tela de detalhes
> [Grupo 35] Adicionar um produto ao carrinho a partir de sua tela de exibição detalhada

- src/components/CartItem.js
- src/components/Product.js
- src/components/ProductList.js
- src/pages/Cart.js
- src/services/addToCart.js
> [Group 16] Product available quantity

- src/App.css
- src/components/CardProduct.jsx
- src/components/ItemCart.jsx
- src/components/ProductDetailsEvaluation.jsx
- src/components/TopBar.jsx
- src/pages/Cart.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
> [Group 6] Main group 6 css pag produtos

- src/App.css
- src/components/FormRating.jsx
- src/components/ProductCard.jsx
- src/components/ProductDetail.jsx
- src/components/ProductSpecs.jsx
- Criação CSS ProductDetails
- Adição de Classname nas divs
- Organização das Divs para o CSS
> [Main-group-18] css-product-details

- src/components/FunctionsToCart.js
- src/components/ListaDeProdutos.jsx
- src/components/Produto.jsx
- src/components/ProdutosDoCarrinho.js
- src/pages/CarrinhoDeCompras.jsx
Criei um arquivo que contem as funções que adicionam e removem os itens do carrinho - a função de remover ainda precisa ser implementada -. Criei também um componente chamado produtos do carrinho, onde ele retorna as informações necessárias para imprimir a DIV na página carrinho de compras.
> Main group 2 requisito 8 adicionando ao carrinho de compras

- src/components/Product.js
- src/components/ProductList.js
> [GROUP 16] - Free shipping 15

- src/components/Add-n-remove.js
* Adiciona componente com função para adicionar ou remover item.
> Enviar componente pra nicole

- src/App.js
- src/pages/Checkout/index.js
- src/pages/ShoppingCart/index.js
> Main group 17 requirement 12

- src/Components/Informations.js
- src/Components/ListCardsProduts.js
> correçao do lint

- src/Components/ListCardsProduts.js
- src/Pages/Cart.js
> correçao do lint segunda tentativa

- src/App.js
- src/Components/CheckoutForm.js
- src/Components/ListProductsCheckout.js
- src/Pages/Checkout.js
- src/Pages/ShoppingCartPage.js
Foi iniciado o desenvolvimento da pagi de checkout
> [Main group 23] pagina checkout

- src/App.js
- src/__tests__/requirement10.test.js
- src/__tests__/requirement9.test.js
- src/components/ProductCartItems.js
- src/components/ProductCartList.js
- src/components/ShoppingCart.js
> Adicionando implementação do requisito 10

- src/pages/ShoppingCart.jsx
Adicionando a feature de soma do carrinho de compras com map e reduce.
> top demais essa 10 - Grupo 3

- src/App.js
- src/components/CategoriesList.jsx
- src/components/ProductCard.jsx
- src/pages/NotFound.jsx
- src/pages/ProductDetails.jsx
- src/pages/ShoppingCart.jsx
- src/pages/index.jsx
- Implementação das funções de desabilitar o botão quando atingir a quantidade disponível do produto
- Adição de indicador de frete grátis na exibição resumida e detalhada do produto
- Criação de "Página não encontrada" quando não existir a rota
> [Grupo 3] Requisitos 14 e 15

- src/components/ProductCard.js
- src/components/ShowCartItems.js
- src/pages/ProductDetails.js
- src/pages/ShoppingCart.js
- src/services/localStorageHandler.js
- Implementação de service para manipulação da quantidade de ítens a ser adicionados ao carrinho por produto no carrinho;
- Adicionado botões para aumentar ou diminuir a quantidade de ítens por produto no carrinho;
> [Grupo 25] Requisito 10

- src/components/CardProduct/index.js
- src/pages/Home/index.js
- src/pages/ProductDetails/index.js
- src/pages/ShopCart/index.js
- src/services/utilities.js
- src/views/AmountControllers/index.js
- src/views/ItemProduct/index.js
> [group 13] realizado requisitos 9, 10 e 11

- src/Routes.jsx
- src/components/Produto.jsx
- src/pages/DetalhesDoProduto.js
Foi criado um componente Detalhes do produto onde as informações são passadas através do storage.
> Requisito 7 feito com base em storage

- src/pages/DetalhesDoProduto.js
Podemos adicionar no carrinho a partir da tela de detalhes
> Main group 2 requisito 9 adicionando ao carrinho de detalhes

- src/components/ShoppingCart.jsx
> [GRUPO 35] Requisito 10 ShoppingCart

- src/App.css
- src/Components/Cart.jsx
- src/Components/Header.jsx
- src/Components/ProductDetails.jsx
- src/Components/ProductList.jsx
- src/Routes.js
Create business rule that receives product through the url, it is already possible to add products from the detail page.
> Add products to cart from details page

- src/components/ShoppingCart.jsx
> Main group 35 req 10 remove

- src/App.css
- src/App.js
- src/components/ProductCard.jsx
- src/components/ProductList.jsx
- src/components/SearchBar.jsx
- src/index.js
- src/pages/Checkout.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
Começando as correções do eslint - Grupo 3.
> Main group 3 requisito 13

- src/App.css
- src/Components/ProductDetails.jsx
Add comment in details product page.
> Comment in detail product

- src/Components/ProductList.jsx
Show free shipping product list.
> Free shipping group 41

- src/Components/ProductList.jsx
Added cart button on list product.
> Add cart button group 41

- src/components/Rating.jsx
- src/pages/productDetails.jsx
> Main group 22 requisito 9

- src/App.js
- src/components/SearchBar.jsx
- src/pages/carrinho.jsx
- src/pages/payment.jsx
> requisito 10

- src/App.js
- src/components/CardProduct.jsx
- src/pages/Home.jsx
- src/pages/ProductDetails.jsx
Refatorando código da página product details
> Refatorando Product Details - 05/12/2020

- src/App.js
- src/pages/FinishCart.jsx
> [Group 6] finish cart

- package-lock.json
- package.json
- src/components/BotoesProduto.js
- src/components/FunctionsToCart.js
- src/components/Produto.jsx
- src/components/ProdutosDoCarrinho.js
- src/pages/CarrinhoDeCompras.jsx
- src/pages/DetalhesDoProduto.js
Modificações em arquivos existentes para implementar a funcionalidade de manipular quantidades por botões.
> Alterações testes para o requisito 10
